services:
#    g_search.example:
#        class: GSearchBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    guzzle:
        class: \GuzzleHttp\Client

# api clients
    api_client:
        class: GSearchBundle\Service\APIClient
        arguments: ['@guzzle', '@service_container']

# service
    search:
        class: GSearchBundle\Service\Search
        arguments: ['@api_client']
        public: true

# validator
    Search_validator:
        class: GSearchBundle\Validator\SearchValidator
